
package com.lanpang.client.com.lanpang.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestService", targetNamespace = "http://webservice.lanpang.com")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface TestService {


    /**
     * 
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "String", targetNamespace = "")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://webservice.lanpang.com", className = "com.lanpang.webservice.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://webservice.lanpang.com", className = "com.lanpang.webservice.SendMessageResponse")
    public String sendMessage(
        @WebParam(name = "username", targetNamespace = "")
        String username);

}
